[build]
publish = "dist"
command = "npm run build"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
